name: closr
description: A new R4I project

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.1.1
  equatable: ^2.0.5
  firebase_core: ^2.3.0
  cloud_firestore: ^4.1.0
  firebase_auth: ^4.1.3
  json_annotation: ^4.7.0
  rive: ^0.9.1
  font_awesome_flutter: ^10.2.1
  hydrated_bloc: ^9.0.0
  path_provider: ^2.0.11
  flutter_native_splash: ^2.2.15
  drag_select_grid_view: ^0.6.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.3.2
  json_serializable: ^6.5.4

flutter_native_splash:
  background_image: "assets/splash_screen.png"
  android_12:
    image: assets/splash_screen.png
    color: "#1a2b47"
  android: true
  ios: false
  web: false

flutter:
  uses-material-design: true
  assets:
    - assets/
